# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jpidata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



DESCRIPTOR = _descriptor.FileDescriptor(
  name='jpidata.proto',
  package='JPI.Cloud.Protobuf.Telemetry',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rjpidata.proto\x12\x1cJPI.Cloud.Protobuf.Telemetry\"D\n\x0bJPIDataPair\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x06intval\x18\x02 \x01'
                b'(\x03H\x00\x12\x10\n\x06strval\x18\x03 \x01(\tH\x00\x42\x05\n\x03val\"^\n\x10JPIDataTimestamp\x12\x11\n\ttimestamp\x18\x01 \x01'
                b'(\r\x12\x37\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32).JPI.Cloud.Protobuf.Telemetry.JPIDataPair\"U\n\x0fJPIDataDelivery\x12\x42\n\ntimestamps\x18\x01 \x03'
                b'(\x0b\x32..JPI.Cloud.Protobuf.Telemetry.JPIDataTimestampb\x06proto3'
)



_JPIDATAPAIR = _descriptor.Descriptor(
  name='JPIDataPair',
  full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataPair.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intval', full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataPair.intval', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strval', full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataPair.strval', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='val', full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataPair.val',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=47,
  serialized_end=115,
)


_JPIDATATIMESTAMP = _descriptor.Descriptor(
  name='JPIDataTimestamp',
  full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataTimestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataTimestamp.timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataTimestamp.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=211,
)


_JPIDATADELIVERY = _descriptor.Descriptor(
  name='JPIDataDelivery',
  full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataDelivery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='JPI.Cloud.Protobuf.Telemetry.JPIDataDelivery.timestamps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=298,
)

_JPIDATAPAIR.oneofs_by_name['val'].fields.append(
  _JPIDATAPAIR.fields_by_name['intval'])
_JPIDATAPAIR.fields_by_name['intval'].containing_oneof = _JPIDATAPAIR.oneofs_by_name['val']
_JPIDATAPAIR.oneofs_by_name['val'].fields.append(
  _JPIDATAPAIR.fields_by_name['strval'])
_JPIDATAPAIR.fields_by_name['strval'].containing_oneof = _JPIDATAPAIR.oneofs_by_name['val']
_JPIDATATIMESTAMP.fields_by_name['data'].message_type = _JPIDATAPAIR
_JPIDATADELIVERY.fields_by_name['timestamps'].message_type = _JPIDATATIMESTAMP
DESCRIPTOR.message_types_by_name['JPIDataPair'] = _JPIDATAPAIR
DESCRIPTOR.message_types_by_name['JPIDataTimestamp'] = _JPIDATATIMESTAMP
DESCRIPTOR.message_types_by_name['JPIDataDelivery'] = _JPIDATADELIVERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JPIDataPair = _reflection.GeneratedProtocolMessageType('JPIDataPair', (_message.Message,), {
  'DESCRIPTOR' : _JPIDATAPAIR,
  '__module__' : 'jpidata_pb2'
  # @@protoc_insertion_point(class_scope:JPI.Cloud.Protobuf.Telemetry.JPIDataPair)
  })
_sym_db.RegisterMessage(JPIDataPair)

JPIDataTimestamp = _reflection.GeneratedProtocolMessageType('JPIDataTimestamp', (_message.Message,), {
  'DESCRIPTOR' : _JPIDATATIMESTAMP,
  '__module__' : 'jpidata_pb2'
  # @@protoc_insertion_point(class_scope:JPI.Cloud.Protobuf.Telemetry.JPIDataTimestamp)
  })
_sym_db.RegisterMessage(JPIDataTimestamp)

JPIDataDelivery = _reflection.GeneratedProtocolMessageType('JPIDataDelivery', (_message.Message,), {
  'DESCRIPTOR' : _JPIDATADELIVERY,
  '__module__' : 'jpidata_pb2'
  # @@protoc_insertion_point(class_scope:JPI.Cloud.Protobuf.Telemetry.JPIDataDelivery)
  })
_sym_db.RegisterMessage(JPIDataDelivery)


# @@protoc_insertion_point(module_scope)
